# Generated by Django 4.1.7 on 2023-04-21 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country', models.CharField(max_length=30)),
                ('City', models.CharField(max_length=169, unique=True)),
                ('WindSpeed', models.IntegerField()),
                ('Humidity', models.IntegerField()),
                ('NowTemp', models.IntegerField()),
                ('TomTemp', models.IntegerField()),
                ('AfTomTemp', models.IntegerField()),
                ('Continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.continent_model')),
            ],
        ),
    ]
