# Generated by Django 4.1.7 on 2023-04-21 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_weather'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_name', models.CharField(max_length=30, unique=True)),
                ('continent_img', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30, unique=True)),
                ('flag', models.TextField(blank=True)),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.continent')),
            ],
        ),
        migrations.CreateModel(
            name='DateWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weather_status', models.CharField(max_length=30)),
                ('status_icon', models.TextField(blank=True)),
                ('wind_speed', models.IntegerField()),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.city')),
            ],
        ),
        migrations.RemoveField(
            model_name='weather',
            name='Continent',
        ),
        migrations.DeleteModel(
            name='Continent_model',
        ),
        migrations.DeleteModel(
            name='Weather',
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.country'),
        ),
    ]
